modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="regentracker"
version="1.0.0"
displayName="Regen Tracker"
description="Отображает регенерацию HP игрока с учетом модификаторов"
authors="xossko"

[[dependencies.regentracker]]
    modId="forge"
    mandatory=true
    versionRange="[47.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.regentracker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
